// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnIJ515vs0y7ICMXI4JdQECa4MVwpEn_A',
    appId: '1:55531643982:web:8002d80ff4016e8bd68f1f',
    messagingSenderId: '55531643982',
    projectId: 'clubverse-4141f',
    authDomain: 'clubverse-4141f.firebaseapp.com',
    storageBucket: 'clubverse-4141f.firebasestorage.app',
    measurementId: 'G-Z79HEG7LTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hU9cK5jfdj2XKh7JqU1M1kzoAIcvi8s',
    appId: '1:55531643982:android:842a21498628d9c2d68f1f',
    messagingSenderId: '55531643982',
    projectId: 'clubverse-4141f',
    storageBucket: 'clubverse-4141f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-hqQ5UhE4cBGldn9y0OTo-Q3pMr71u4',
    appId: '1:55531643982:ios:b08d45801df547a8d68f1f',
    messagingSenderId: '55531643982',
    projectId: 'clubverse-4141f',
    storageBucket: 'clubverse-4141f.firebasestorage.app',
    iosBundleId: 'com.example.uniclub',
  );
}
